### ISSUE TITLE
Using a really long array gets cut off in the GUI.

### ISSUE THREAD

**Issue by onyxromero** [Toma1O6/Configuration#14]
I really don't know how to explain this, but in my mod, there is a really long array with multiple settings in the array and a good part of them gets cut off by the GUI.

Like, this is the default array for an iron golem's settings:

"minecraft:iron_golem=true,true,0,0,0.0,0.0,false,2"

Half of it gets cut off. Can you increase the limit to how many characters show up per string please?

**Comment by Toma1O6** [comment]
If I understand this issue correctly then the best solution for you might be the [CharacterLimit](https://github.com/Toma1O6/Configuration/wiki/Improving-config-values#characterlimit) annotation, which allows you to configure the limits for text boxes in GUI.
Another possible solution would be to create new configurable object with these attributes as fields instead of parsing string, but that depends on your use case.

**Comment by kobaltromero** [comment]
Thank you Toma. Also, I can do that? Like I can create a object for each entity override? Like how would I do that? Players are supposed to be able to do overrides for ANY entity, modded or vanilla.

**Comment by Toma1O6** [comment]
Oh, if it is supposed to be for all entities, even modded then that is currently not supported. I'd have to implement support for dynamic config values
